### ISSUE TITLE
Cannot Get Price or Menu_ID to be created in the Order_items Database

### ISSUE THREAD

**Issue by timhilton** [timhilton/RESTaurant#3]
Issue: Cannot Get Price or Menu_ID to be created in the Order_items Database

What I tried:  I tried adding <%= @menus.item_price%> into the select form - it just added the price to the menu item.  I tried adding the @orders.item_price into the select form - it broke it.  I looked at the belongs_to has_many...  I think it looks okay.  I'm kinda stuck.

**Comment by timhilton** [comment]
Andrew helped me fix it.  Then I created a server/waiter param...  then it broke.  :(

![screen shot 2015-08-26 at 2 06 23 pm](https://cloud.githubusercontent.com/assets/11655608/9501836/b0c60d52-4bfb-11e5-9a70-ba7ef63bb408.png)

**Comment by amadden80** [comment]
*in person*
