### ISSUE TITLE
Make order post while on party page - redirect issue

### ISSUE THREAD

**Issue by timhilton** [timhilton/RESTaurant#4]
Can't stay on the table page (party) when adding a new item.  Can't make the post redirect to the table page.

Tried messing with the routes.  Tried messing with the posts...

**Comment by rapala61** [comment]
commit and push all your code, point me to the files I should be looking at to help you.

**Comment by timhilton** [comment]
Andrew helped with with the order post on party page - which is now resolved.  The delete feature on party page same issue.  orders_controller.rb orders/show.erb

**Comment by timhilton** [comment]
Fixed it.  All good.  Thanks!
